version: '2'
services:
  dind-proxy:
    image: 5003/test:dind-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: true